package com.softeem.ssm.mapper;

import com.softeem.ssm.pojo.Products;
import com.softeem.ssm.pojo.ProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int insertSelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    Products selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int updateByExampleSelective(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int updateByExample(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int updateByPrimaryKeySelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    int updateByPrimaryKey(Products record);
}