package com.softeem.ssm.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Cart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.img_path
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.name
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.price
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.quantity
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.uid
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cart
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.id
     *
     * @return the value of t_cart.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.id
     *
     * @param id the value for t_cart.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.img_path
     *
     * @return the value of t_cart.img_path
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.img_path
     *
     * @param imgPath the value for t_cart.img_path
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.name
     *
     * @return the value of t_cart.name
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.name
     *
     * @param name the value for t_cart.name
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.price
     *
     * @return the value of t_cart.price
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.price
     *
     * @param price the value for t_cart.price
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.quantity
     *
     * @return the value of t_cart.quantity
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.quantity
     *
     * @param quantity the value for t_cart.quantity
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.total
     *
     * @return the value of t_cart.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.total
     *
     * @param total the value for t_cart.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.uid
     *
     * @return the value of t_cart.uid
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.uid
     *
     * @param uid the value for t_cart.uid
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Cart other = (Cart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getImgPath() == null ? other.getImgPath() == null : this.getImgPath().equals(other.getImgPath()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getImgPath() == null) ? 0 : getImgPath().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imgPath=").append(imgPath);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", quantity=").append(quantity);
        sb.append(", total=").append(total);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}