package com.softeem.ssm.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Orders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.pay_data
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Date payData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.status
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.user_id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_orders
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.id
     *
     * @return the value of t_orders.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.id
     *
     * @param id the value for t_orders.id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.pay_data
     *
     * @return the value of t_orders.pay_data
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Date getPayData() {
        return payData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.pay_data
     *
     * @param payData the value for t_orders.pay_data
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setPayData(Date payData) {
        this.payData = payData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.status
     *
     * @return the value of t_orders.status
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.status
     *
     * @param status the value for t_orders.status
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.total
     *
     * @return the value of t_orders.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.total
     *
     * @param total the value for t_orders.total
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.user_id
     *
     * @return the value of t_orders.user_id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.user_id
     *
     * @param userId the value for t_orders.user_id
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orders other = (Orders) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayData() == null ? other.getPayData() == null : this.getPayData().equals(other.getPayData()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayData() == null) ? 0 : getPayData().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbggenerated Sun Oct 22 16:14:48 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payData=").append(payData);
        sb.append(", status=").append(status);
        sb.append(", total=").append(total);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}